[project]
name = "robostack"
description = "Development environment for RoboStack ROS packages"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]

# This will automatically activate the ros workspace on activation
[target.win.activation]
scripts = ["install/setup.bat"]

[target.unix.activation]
# For activation scripts, we use bash for Unix-like systems
scripts = ["install/setup.bash"]

[target.win-64.dependencies]
# vs2022_win-64 = "*"  # Uncomment if using Visual Studio 2022

# Define the build task
[feature.build.target.unix.tasks.build]
cmd = "colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

# Define the clean task
[feature.build.target.unix.tasks.clean]
cmd = "rm -rf build install log"

# Define the run-driver task
[feature.build.target.unix.tasks.run-driver]
cmd = ["bash", "-c", ". install/setup.bash && ros2 launch spinnaker_camera_driver driver_node.launch.py camera_type:=blackfly_s serial:='20435008'"]

# Define the rebuild task
[feature.build.target.unix.tasks.rebuild]
depends-on = ["clean", "build"]

# Dependencies used by all environments
[dependencies]
python = "*"
# Build tools
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
# ROS specific tools
rosdep = "*"
colcon-common-extensions = "*"

[target.linux.dependencies]
libgl-devel = "*"

# Define all the different ROS environments
# Each environment corresponds to a different ROS distribution
# and can be activated using the `pixi run/shell -e <environment>` command.
[environments]
humble = { features = ["humble", "build"] }

### ROS Humble ####
[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
ros-humble-desktop = "*"
ros-humble-camera-info-manager = ">=3.1.12,<4"
ros-humble-ament-cmake-clang-format = ">=0.12.12,<0.13"